### CCAA Python Training Part 2
<p> Date Created: September 8th 2021 </p>
<p> Created By: Analyst 134 </p> 
<p> Data Sources and Examples Located in NFCAPythonTraining.ipynb </p>

In [2]:
# import libraries 
import pandas as pd
import numpy as np 
import os 
import geopandas as gpd
import calmap
import calplot
import matplotlib.pyplot as plt

In [3]:
# Pull data frame from the pervious notebook into this notebook to start building frequency tables for the Chief
%store -r Denver_Crimes_2020
pd.set_option('display.max_rows', 82429)
Denver_Crimes_2020.head()

,year,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,...,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC,New_Date,Months,monthName
0,2020,2.020132e+09,2.020000e+15,5707,0,criminal-trespassing,all-other-crimes,2/29/2020 20:15,NaN,2/29/2020 21:16,...,-104.988366,39.754698,6.0,611.0,five-points,1,0,2020-02-29,2,February
1,2020,2.020121e+09,2.020000e+15,5441,0,traffic-accident,traffic-accident,2/25/2020 11:00,NaN,2/25/2020 11:02,...,-104.975266,39.730449,6.0,623.0,capitol-hill,0,1,2020-02-25,2,February
2,2020,2.020298e+08,2.020000e+14,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,1/13/2020 23:00,1/14/2020 5:00,1/14/2020 11:07,...,-105.010399,39.679879,4.0,422.0,college-view-south-platte,1,0,2020-01-14,1,January
3,2020,2.020431e+08,2.020000e+14,5212,1,weapon-by-prev-offender-powpo,all-other-crimes,1/20/2020 2:02,NaN,1/20/2020 3:36,...,-104.988962,39.752955,6.0,611.0,five-points,1,0,2020-01-20,1,January
4,2020,2.020466e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/21/2020 15:43,NaN,1/21/2020 17:13,...,-104.891880,39.784132,5.0,511.0,stapleton,1,0,2020-01-21,1,January

## Step 3: Create Frequency Tables 2020 Denver Data  Frequency Tables 
<p> <a href="http://hamelg.blogspot.com/2015/11/python-for-data-analysis-part-19_17.html"> How to Create Frequency Tables </a></p> 
<p> Frequency Tables in Python are useful for looking at one variable. If you need to compare two columns, look at pivot tables. Note: piviot tables cant compare columns that have duplicates</p> 
</p>
<p><a href="https://towardsdatascience.com/a-step-by-step-guide-to-pandas-pivot-tables-e0641d0c6c70"> How to Create Pivot Tables </a></p>

### Crime Types

In [4]:
# Total Number of Offenses 
DCrimes = pd.crosstab(Denver_Crimes_2020.OFFENSE_CATEGORY_ID, columns ='count')
# percentages 
DCrimes['percent'] = (DCrimes['count'] / DCrimes['count'].sum()) * 100
# format percentages so a % symbol shows up 
DCrimes['percent'] = DCrimes['percent'].map('{:,.2f}%'.format)
# Call your frequency table by your dataframke variable
DCrimes.sort_values(by='count',ascending=False)

col_0                         count percent
OFFENSE_CATEGORY_ID
traffic-accident              14603  17.72%
all-other-crimes              12012  14.57%
theft-from-motor-vehicle      10179  12.35%
larceny                        9851  11.95%
public-disorder                9762  11.84%
auto-theft                     8273  10.04%
burglary                       5141   6.24%
other-crimes-against-persons   3911   4.74%
aggravated-assault             2892   3.51%
drug-alcohol                   2538   3.08%
robbery                        1177   1.43%
white-collar-crime             1146   1.39%
sexual-assault                  705   0.86%
arson                           154   0.19%
murder                           85   0.10%

### Neighborhoods Crime Rate

In [5]:
# Next Frequency Table Consists of Neighborhoods 
Neighborhoods =  pd.crosstab(Denver_Crimes_2020.NEIGHBORHOOD_ID, columns ='count')
# Get percentages 
Neighborhoods['percent'] = (Neighborhoods['count']/Neighborhoods['count'].sum()) * 100
# Format Percentages 
Neighborhoods['percent'] = Neighborhoods['percent'].map('{:,.2f}%'.format)
# Call dataframe 
Neighborhoods.sort_values(by='count',ascending=False)

col_0                       count percent
NEIGHBORHOOD_ID
five-points                  4431   5.38%
capitol-hill                 3363   4.08%
montbello                    2653   3.22%
cbd                          2576   3.13%
gateway-green-valley-ranch   2283   2.77%
stapleton                    2228   2.70%
union-station                2129   2.58%
lincoln-park                 2044   2.48%
baker                        2035   2.47%
civic-center                 2016   2.45%
east-colfax                  1788   2.17%
west-colfax                  1687   2.05%
hampden                      1680   2.04%
northeast-park-hill          1679   2.04%
north-capitol-hill           1655   2.01%
westwood                     1625   1.97%
dia                          1607   1.95%
central-park                 1585   1.92%
highland                     1555   1.89%
hampden-south                1520   1.84%
speer                        1420   1.72%
elyria-swansea               1265   1.53%
globeville                   1233   1.50%
washington-virginia-vale     1164   1.41%
cheesman-park                1114   1.35%
mar-lee                      1097   1.33%
villa-park                   1095   1.33%
city-park-west               1084   1.32%
virginia-village             1009   1.22%
ruby-hill                    1008   1.22%
athmar-park                   977   1.19%
overland                      963   1.17%
harvey-park                   961   1.17%
college-view-south-platte     960   1.16%
sunnyside                     928   1.13%
congress-park                 919   1.11%
cherry-creek                  878   1.07%
windsor                       831   1.01%
berkeley                      816   0.99%
west-highland                 796   0.97%
goldsmith                     747   0.91%
lowry-field                   742   0.90%
washington-park-west          729   0.88%
barnum                        719   0.87%
jefferson-park                698   0.85%
hale                          688   0.83%
university-park               663   0.80%
montclair                     654   0.79%
harvey-park-south             629   0.76%
sloan-lake                    627   0.76%
marston                       600   0.73%
platt-park                    595   0.72%
valverde                      593   0.72%
south-park-hill               576   0.70%
university-hills              571   0.69%
clayton                       549   0.67%
university                    548   0.66%
bear-valley                   543   0.66%
north-park-hill               523   0.63%
southmoor-park                519   0.63%
cole                          509   0.62%
auraria                       500   0.61%
hilltop                       497   0.60%
whittier                      486   0.59%
sun-valley                    457   0.55%
belcaro                       454   0.55%
regis                         452   0.55%
kennedy                       443   0.54%
washington-park               434   0.53%
chaffee-park                  430   0.52%
barnum-west                   418   0.51%
city-park                     412   0.50%
fort-logan                    387   0.47%
cory-merrill                  376   0.46%
skyland                       302   0.37%
rosedale                      251   0.30%
country-club                  204   0.25%
indian-creek                  155   0.19%
wellshire                      91   0.11%

In [6]:
# Show Top 5 Neighborhoods for Denver Based on number of Crimes Reported. 
Top5 = Denver_Crimes_2020.groupby(['NEIGHBORHOOD_ID']).NEIGHBORHOOD_ID.value_counts().nlargest(5)
Top5

NEIGHBORHOOD_ID             NEIGHBORHOOD_ID
five-points                 five-points                   4431
capitol-hill                capitol-hill                  3363
montbello                   montbello                     2653
cbd                         cbd                           2576
gateway-green-valley-ranch  gateway-green-valley-ranch    2283
Name: NEIGHBORHOOD_ID, dtype: int64

### Frequency By Month

In [6]:
# Next Frequency Table Consists of Months 
Months =  pd.crosstab(Denver_Crimes_2020.monthName, columns ='count')
# Get percentages 
Months['percent'] = (Months['count']/Months['count'].sum()) * 100
# Format Percentages 
Months['percent'] = Months['percent'].map('{:,.2f}%'.format)
# Call dataframe 
Months.sort_values(by='count',ascending=False)

col_0      count percent
monthName
August      7746   9.40%
January     7666   9.30%
October     7587   9.20%
September   7559   9.17%
July        7500   9.10%
November    6939   8.42%
February    6889   8.36%
May         6699   8.13%
June        6647   8.06%
March       6049   7.34%
December    5791   7.03%
April       5357   6.50%